- hosts: localhost
  become: true
  pre_tasks:
    - name: install git
      apt: name=git
    - name: update repositories
      apt: update_cache=yes
      changed_when: false
  tasks:
    - include: tasks/packages.yml
